apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 497330445336.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-backend:bc1778f
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI