apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend
          image: 497330445336.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-frontend:33e7535
          imagePullPolicy: Always
          ports:
            - containerPort: 80