name: CI - Build Scan Push

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      BACKEND_REPO: expense-tracker-backend
      FRONTEND_REPO: expense-tracker-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build Backend
        run: docker build -t backend ./backend

      - name: Scan Backend
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: backend
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Push Backend
        run: |
          docker tag backend ${{ steps.ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:${{ env.TAG }}
          docker push ${{ steps.ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:${{ env.TAG }}

     
      - name: Build Frontend
        run: docker build -t frontend ./frontend

      - name: Scan Frontend
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: frontend
          severity: HIGH,CRITICAL
          exit-code: 0

      - name: Push Frontend
        run: |
          docker tag frontend ${{ steps.ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:${{ env.TAG }}
          docker push ${{ steps.ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:${{ env.TAG }}

      - name: Update backend deployment manifest
        run: |
          sed -i "s|image: .*expense-tracker-backend:.*|image: ${{ steps.ecr.outputs.registry }}/${{ env.BACKEND_REPO }}:${{ env.TAG }}|g" k8s/backend/backend-deployment.yaml

      - name: Update frontend deployment manifest
        run: |
          sed -i "s|image: .*expense-tracker-frontend:.*|image: ${{ steps.ecr.outputs.registry }}/${{ env.FRONTEND_REPO }}:${{ env.TAG }}|g" k8s/frontend/frontend-deployment.yaml

     
      - name: Commit and push updated manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add k8s/backend/backend-deployment.yaml k8s/frontend/frontend-deployment.yaml
          git diff --cached --quiet || git commit -m "Update image tags to ${TAG}"
          git push